### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by GCorbel** [phrase/slimkeyfy#5]
Hi, I'm trying to use slimkeyfy to extract french text and I have this error : 

```
/usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy/console/translate.rb:11:in `split': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy/console/translate.rb:11:in `initialize'
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy/console/command_line.rb:83:in `new'
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy/console/command_line.rb:83:in `translate'
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy/console/command_line.rb:70:in `block in directory_translate'
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy/console/command_line.rb:67:in `each'
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy/console/command_line.rb:67:in `directory_translate'
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy/console/command_line.rb:56:in `run'
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/lib/slimkeyfy.rb:5:in `translate'
        from /usr/local/bundle/bundler/gems/slimkeyfy-3b3cf8e7983b/bin/slimkeyfy:5:in `<top (required)>'
        from /usr/local/bundle/bin/slimkeyfy:16:in `load'
        from /usr/local/bundle/bin/slimkeyfy:16:in `<main>'
```

It does not like special chars like èéà, etc.

**Comment by sacry-dyn** [comment]
@GCorbel sorry for the late reply. We will look into this and come back to you.

**Comment by sacry-dyn** [comment]
@GCorbel I cannot say what the actual reason is that you are getting this error. We investigated a bit with different languages and the tool does not crash due to encoding issues. Do you have a sample file to reproduce this?

**Comment by GCorbel** [comment]
It seems to works now. I close this issue.
